### ISSUE TITLE
lint

### ISSUE THREAD

**Issue by bbigras** [matiasinsaurralde/go-dotnet#3]
You should check http://go-lint.appspot.com/github.com/matiasinsaurralde/go-dotnet.

Do you know that only functions starting with a capital letters are exported (usable outside of your module)? You only export the functions that are needed by people who want to use your module and only the exported functions will show up on godoc and keep it simple.

[gometalinter](https://github.com/alecthomas/gometalinter) is nice too.

**Comment by matiasinsaurralde** [comment]
Thanks, I'll polish the API in the following weeks, this is very useful.

**Comment by matiasinsaurralde** [comment]
Thanks for all the contributions, I'm currently rewriting this project and working on a code generation tool to make .NET/Go integrations easier, if you're interested keep an eye on `master`.
I'm closing this for now!
