### ISSUE TITLE
TRUSTED_PLATFORM_ASSEMBLIES line maintainability questioned

### ISSUE THREAD

**Issue by omac777** [matiasinsaurralde/go-dotnet#5]
https://github.com/matiasinsaurralde/go-dotnet/blob/master/examples/http.go#L22

I understand you're producing miracles here to make .NET interoperate with golang and that's well-appreciated.

The only beef I have is the maintainability of certain lines to make it happen.
TRUSTED_PLATFORM_ASSEMBLIES and what you assign to it makes it very difficult to isolate what changes over time on that one line.  There are too many things happening on it.
I understand by doing so it will load up faster but I imagine later you're going to want to place more trusted platform assemblies and different versions of them might conflict with each other which is where I believe a great deal of effort will be spent examining differences if left in its current one-line FOR EVERYTHING state.  It's the long-term maintainability of that one line I question.

**Comment by matiasinsaurralde** [comment]
Thanks, all these properties represent what I've been testing on my computer, I'm open to ideas about maintainability and ways of dealing with this!

**Comment by matiasinsaurralde** [comment]
It's better now 👍
