### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by joeblew99** [matiasinsaurralde/go-dotnet#7]
Interesting work. I am also playing around with this idea.

.NET Standard 2.0 can out a few days ago and i jumped on it because it provides a base for using c# cross OS (Win, MAC; IOS , Android, Linux).

https://github.com/dotnet/standard/blob/master/docs/versions.md

Its Microsofts new way of getting c# working everywhere and so seems to me to be the best base moving forward on your project perhaps. 
Let me know what you think ....

So in order to use this new stuff there are a few things that need to be changed in your code.

````

x-MacBook-Pro:gedw99 apple$ dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help            Display help.
  --version         Display version.

path-to-application:
  The path to an application .dll file to execute.
x-MacBook-Pro:gedw99 apple$ dmcs
Note: dmcs is deprecated, please use mcs instead!
error CS2008: No files to compile were specified
Compilation failed: 1 error(s), 0 warnings
````

**Comment by matiasinsaurralde** [comment]
Thanks, sounds interesting. I would like to continue working on this project in the next months, in case you have any PR idea, send it over!

**Comment by matiasinsaurralde** [comment]
Also I'm interested on this kind of approach (it could make it an useful package): https://github.com/matiasinsaurralde/go-dotnet/blob/master/code_generation.md

**Comment by joeblew99** [comment]
its not really useful  for me.
I need to call golang from .NET. YOu have it working the other way only right ?

At the moment i use Protobufs to do calls between c# and .net.

**Comment by matiasinsaurralde** [comment]
Ah I see, this doesn't work the other way 😢

**Comment by joeblew99** [comment]
OK i got it working using GRPC and protobuf.
