### ISSUE TITLE
I can't open a dll written in c#

### ISSUE THREAD

**Issue by Demitroi** [matiasinsaurralde/go-dotnet#8]
Hello great work!

I was trying to call a method written in c#, but when i run i get the next error.

```
# github.com/matiasinsaurralde/go-dotnet
could not determine kind of name for C.getSize
could not determine kind of name for C.initDelegateArguments
could not determine kind of name for C.pushDelegateArgument
```

The dll of c# is in the same folder. The implementation code is the next.

```go
propeties := map[string] string{
		"TRUSTED_PLATFORM_ASSEMBLIES": "C:\\Program Files (x86)\\Reference
Assemblies\\Microsoft\\Framework\\.NETCore\\v4.5",
		"APP_PATHS": "C:\\Users\\Sergio\\Desktop\\TerminalGO",
		"NATIVE_DLL_SEARCH_DIRECTORIES": "C:\\Users\\Sergio\\Desktop\\TerminalGO",
	}
	runtime, errorso := dotnet.NewRuntime(dotnet.RuntimeParams{
		Properties: propeties,
		ManagedAssemblyAbsolutePath: "SumaString.dll"})

	fmt.Sprintln(runtime)
	defer runtime.Shutdown()

	if errorso != nil {
		panic(errorso)
	}
```

The c# code is the next

```csharp
namespace SumaString
{
    public class SumaString
    {
        public string Sumar(string n1, string n2)
        {
            return (Convert.ToDouble(n1) + Convert.ToDouble(n2)).ToString();
        }
    }
}
```

Need i to indicate the .net libraries or can be another error?

**Comment by Demitroi** [comment]
Windows 10 x64, GO 1.8

**Comment by Nicomedis** [comment]
`# github.com/matiasinsaurralde/go-dotnet
github.com\matiasinsaurralde\go-dotnet\delegate.go:20:7: could not determine kind of name for C.getSize
github.com\matiasinsaurralde\go-dotnet\delegate.go:44:8: could not determine kind of name for C.initDelegateArguments
github.com\matiasinsaurralde\go-dotnet\delegate.go:38:3: could not determine kind of name for C.pushDelegateArgument`

I got the same issue on Windows 10 x64 , GO 1.9

**Comment by ellinorcrux** [comment]
I'm also running into this issue. Any workarounds? What libraries am I looking for exactly? (sorry, I'm a C# n00b)

**Comment by matiasinsaurralde** [comment]
I'm currently refactoring the project and looking forward to implement a stable and flexible package!
